from __future__ import annotations

from datetime import date, datetime
from html import escape
from pathlib import Path
from typing import Any, Dict

_TEMPLATE_PATH = Path(__file__).resolve().parents[1] / "templates" / "ipo_alert_email.html"


def _format_closing_date(closing_date: str) -> str:
    if not closing_date:
        return "N/A"

    try:
        parsed = datetime.fromisoformat(closing_date)
    except ValueError:
        try:
            parsed = datetime.strptime(closing_date, "%d-%m-%Y")
        except ValueError:
            try:
                parsed = datetime.strptime(closing_date, "%d/%m/%Y")
            except ValueError:
                try:
                    parsed = datetime.strptime(closing_date, "%d%m%Y")
                except ValueError:
                    if len(closing_date) >= 8:
                        try:
                            parsed = datetime.strptime(closing_date, "%Y-%m-%d")
                        except ValueError:
                            return closing_date
                    else:
                        return closing_date

    today = date.today()
    if parsed.date() == today:
        return "Today"

    return parsed.strftime("%d %b %Y")


def render_trigger_email_template(company: str, trigger: Dict[str, Any], closing_date: str) -> tuple[str, str]:
    formatted = _format_closing_date(closing_date)
    trigger_text = f"{trigger['operator']} {trigger['threshold']:.2f}x"
    subject = f"IPO trigger alert: {company} reached {trigger_text}"

    plain_text = (
        f"IPO alert for {company}.\n\n"
        f"The overall subscription reached {trigger_text}.\n"
        f"Closing date: {formatted}.\n\n"
        "This alert was generated by Hermes IPO Monitor."
    )

    template = _TEMPLATE_PATH.read_text(encoding="utf-8")
    rendered_html = template
    replacements = {
        "__COMPANY__": company,
        "__TRIGGER__": trigger_text,
        "__CLOSING_DATE__": formatted,
    }
    for placeholder, value in replacements.items():
        rendered_html = rendered_html.replace(placeholder, escape(str(value)))

    return subject, rendered_html if "<html" in rendered_html.lower() else plain_text
