from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict

_TEMPLATE_PATH = Path(__file__).resolve().parent / "templates" / "ipo_alert_email.html"


def _format_closing_date(closing_date: str) -> str:
    formatted = ""
    try:
        parsed = datetime.fromisoformat(closing_date)
        formatted = parsed.strftime("%d%m%Y")
    except ValueError:
        if len(closing_date) >= 8:
            formatted = closing_date[:2] + closing_date[3:5] + closing_date[6:8]
    return formatted or "N/A"


def render_trigger_email_template(company: str, trigger: Dict[str, Any], closing_date: str) -> tuple[str, str]:
    formatted = _format_closing_date(closing_date)
    trigger_text = f"{trigger['operator']} {trigger['threshold']:.2f}x"
    subject = f"IPO trigger alert: {company} reached {trigger_text}"

    plain_text = (
        f"IPO alert for {company}.\n\n"
        f"The overall subscription reached {trigger_text}.\n"
        f"Closing date: {formatted}.\n\n"
        "This alert was generated by Hermes IPO Monitor."
    )

    template = _TEMPLATE_PATH.read_text(encoding="utf-8")
    rendered_html = template
    replacements = {
        "__COMPANY__": company,
        "__TRIGGER__": trigger_text,
        "__CLOSING_DATE__": formatted,
    }
    for placeholder, value in replacements.items():
        rendered_html = rendered_html.replace(placeholder, str(value))

    return subject, rendered_html if "<html" in rendered_html.lower() else plain_text
