CREATE TABLE IF NOT EXISTS snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at TEXT NOT NULL,
    source_url TEXT NOT NULL,
    item_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ipo_subscriptions (
    snapshot_id INTEGER NOT NULL,
    ipo_id TEXT NOT NULL,
    company TEXT NOT NULL,
    qib_subscription DOUBLE PRECISION,
    nii_subscription DOUBLE PRECISION,
    retail_subscription DOUBLE PRECISION,
    overall_subscription DOUBLE PRECISION,
    closing_date DATE,
    FOREIGN KEY (snapshot_id) REFERENCES snapshots(id)
);

CREATE TABLE IF NOT EXISTS mailing_lists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    emails TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mail_triggers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    trigger_type TEXT NOT NULL DEFAULT 'overall_subscription',
    threshold DOUBLE PRECISION NOT NULL,
    operator TEXT NOT NULL CHECK(operator IN ('>', '>=', '<', '<=', '=', '==')),
    mailing_list_id INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    FOREIGN KEY (mailing_list_id) REFERENCES mailing_lists(id)
);

CREATE TABLE IF NOT EXISTS trigger_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_id INTEGER NOT NULL,
    ipo_id TEXT NOT NULL,
    company TEXT NOT NULL,
    trigger_threshold DOUBLE PRECISION NOT NULL,
    operator TEXT NOT NULL,
    closing_date TEXT,
    sent_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'sent',
    subject TEXT,
    body TEXT,
    message TEXT,
    UNIQUE (trigger_id, ipo_id)
);

CREATE TABLE IF NOT EXISTS ipo_notifications (
    ipo_id TEXT PRIMARY KEY,
    paused BOOLEAN NOT NULL DEFAULT FALSE,
    paused_at TEXT,
    reason TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ipo_subscriptions ADD COLUMN IF NOT EXISTS closing_date DATE;
